# Generated by Django 4.1 on 2022-09-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('pwd', models.CharField(max_length=100)),
                ('roleid', models.IntegerField()),
            ],
            options={
                'db_table': 'usermaster',
            },
        ),
    ]
