# Generated by Django 4.1 on 2022-09-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreg',
            old_name='roleid',
            new_name='role_id',
        ),
    ]
