# Generated by Django 4.1 on 2022-09-29 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='address_city',
            field=models.CharField(default='NULL', max_length=150),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='customer_name',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
