# Generated by Django 4.1 on 2022-12-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='picklist_assignment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pickid', models.CharField(max_length=50)),
                ('picker_id', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('row', models.IntegerField()),
                ('rack', models.IntegerField()),
                ('shelf', models.IntegerField()),
                ('status', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
